### ISSUE TITLE
append_default_dir_paths needs to take care of duplicate paths

### ISSUE THREAD

**Issue by krab** [nuspell/nuspell#107]
https://github.com/nuspell/nuspell/blob/master/src/nuspell/finder.cxx#L85

Tl;dr; currently on my ubuntu in virtual machine i have scuffed env paths like this: 
` XDG_DATA_DIRS="/usr/share/xfce4:/usr/share/xubuntu:/usr/local/share/:/usr/share/:/var/lib/snapd/desktop:/usr/share"
` 
it contains `/usr/share/:` and `/user/share:` this ends up with duplicates in list of dictionaries:

```
en_US /usr/share//hunspell/en_US
ru_RU /usr/share//hunspell/ru_RU
en_US /usr/share/hunspell/en_US
ru_RU /usr/share/hunspell/ru_RU
```

**Comment by dimztimz** [comment]
This is a feature not a bug. The [XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) says nothing about duplicate directory paths, says something only about the order.

Why is your environment variable like that? Maybe you can fix it by removing the last directory path from the variable.
