### ISSUE TITLE
Question regardin dictionary format

### ISSUE THREAD

**Issue by AvtechScientific** [nuspell/nuspell#112]
As far as I understand from the webpage - nuspell supports hunspell dictionaries. My questions is:

1) does nuspell supports **also** hunspell dictionaries but has it's own primary format (and if yes - what is this primary format),
or
2) nuspell supports **only** hunspell dictionaries?

Thank you!

**Comment by PanderMusubi** [comment]
At the moment, Nuspell supports only Hunspell dictionaries.

**Comment by AvtechScientific** [comment]
1. from what I have understood from Wikipedia hunspell uses myspell dictionary format, am I right?
2. if yes, then Nuspell is compatible with at least two other spell checkers - hunspell and myspell, correct?
3. are there additional spell checkers that Nuspell is compatible with them via dictionary format?

Thank you!
PS: I'm trying to find a proper spell checker for my new project, that's why this research...

**Comment by PanderMusubi** [comment]
Since Myspell, the format has been a little bit extended by Hunspell. Since Myspell is not around anymore, that is not a problem. All dictionaries Myspell and dictionaries Hunspell can be used by Nuspell.
