### ISSUE TITLE
Question: Is it possible to get a list of all words in a dictionary?

### ISSUE THREAD

**Issue by erichlf** [nuspell/nuspell#116]
I am creating some software that needs to find anagrams and so I need a list of words. I also want to spell check words, so I figured maybe I could get the list of words to build anagrams directly from nuspell. Is this possible? if so what would the code look like? I envision being able to do something like
```
std::vector<std::string> words = nuspell.get_word_list();
```
This list would hopefully include the infinitive, conjugations, declension, etc. Is this possible?

**Comment by PanderMusubi** [comment]
You can find word lists here https://github.com/nuspell/nuspell/wiki/Dictionaries-and-Contacts#4-word-list-contacts and you can check words with Nuspell one by one.

**Comment by erichlf** [comment]
So the answer is no there is no way to get the word list directly from nuspell?

**Comment by PanderMusubi** [comment]
Nope.
