### ISSUE TITLE
Do not spellcheck URLs and file paths / names

### ISSUE THREAD

**Issue by tad-lispy** [nuspell/nuspell#119]
# Change/feature request

Hello! Thanks for your work on Nuspell. 

I'm trying to get a spell checking system for a static website generator. The intention is to use it in a CI, so it has to work without human assistance and produce no false-positives. More background here: <https://stackoverflow.com/q/71818283/1151982>. With Nuspell I have it _almost_ working. The one remaining blocker is that it checks the spelling in URL strings and filenames. In this regard both Hunspell and Aspell behave better.

Given this `sample.txt` file:

``` text
Since you’ve gone I’ve been loost without a trace.

Asking about Node.js at https://stackoverflow.com/questions/71818283/

All my rants are on https://tad-lispy.com/. Including pic22.png.
```

I'm getting this results

```
$ nuspell -l sample.txt
INFO: Locale LC_CTYPE=en_US.UTF-8, Used encoding=UTF-8
INFO: Pointed dictionary /nix/store/b99hqd4l8ng3x3qb3n82687hh8s5i7d3-hunspell-dict-en-us-large-wordlist-2018.04.16/share/hunspell/en_US.{dic,aff}
loost
Node.js
https
stackoverflow.com
https
lispy.com
pic22
png
```

With "Node.js" I can deal with by providing a custom dictionary, but I don't know how to work around the "https", "stackoverflow.com", "lispy.com", "pic22" and "png" false positives. I believe they should not be detected as misspelled because these words are either part of a URL or a filename.

**Comment by dimztimz** [comment]
This is beyond the scope of the CLI tool. It is designed only for natural languages in plain text. There is no support for technical texts with special notation nor for file-formats like HTML, Markdown, etc.
