### ISSUE TITLE
Incosistent advice on comments

### ISSUE THREAD

**Issue by itsagoodbrain** [nuspell/nuspell#121]
- Others, questions

In the [comments section](https://github.com/nuspell/nuspell/wiki/Dictionary-File-Format#32-comments) of the wiki the following advice is given:

> Full comment lines should be avoided. Comments at the very end of lines with pound sign (#) are OK.

However the complex example under the [examples section](https://github.com/nuspell/nuspell/wiki/Dictionary-File-Format#12-examples) includes multiple:

> 
```
# A line with only comment
5
one
two	po:number
three # comment at end of a line
four/T
friend/ABt po:noun
    # A line with whitespace and comment
 ```

**Comment by dimztimz** [comment]
fixed, thanks see again
