### ISSUE TITLE
Addition to dictionary maintainers for sk_SK

### ISSUE THREAD

**Issue by richo67** [nuspell/nuspell#125]
- Others, questions

# Other issues

I would suggest to add link to web page for maintainers of sk_SK dictionaries in the wiki page.
The web page for them is https://sk-spell.sk.cx/

Thank you.
P.S.: Maybe I could do it myself, but I do not know how. Thank you for your  understanding.

**Comment by PanderMusubi** [comment]
Thanks fro your contribution. The URL has been added with https://github.com/nuspell/nuspell/wiki/Dictionaries-and-Contacts/30f8fc420f1841a4b7542160f3a398b8aec2d34f
