### ISSUE TITLE
errors when using hunspell dict sk_SK

### ISSUE THREAD

**Issue by richo67** [nuspell/nuspell#126]
- Bug reports

# Reporting bugs

When reporting a bug you must tell us the state of your system and the
steps to reproduce the bug. For the state please specify the following:

| key                                       | value |
|-------------------------------------------|-------|
| Operating system, distribution, version = |    Latest Manjaro GNOME 43.1   |
| Nuspell version                         = |    5.1.2   |
| Dictionary, package name, version       = |    sk_SK hunspell 2.4.6 from  https://github.com/sk-spell/hunspell-sk/releases/tag/v2.4.6   |
| Command-line tool or GUI application    = |   command line     |

## Steps to reproduce
after installing sk_SK aff and dic files run
nuspell -d sk_SK

## Bugged behavior (output)

Please see attached error.log.gz

## Expected behavior (output)
No warnings  ;-)
As I am beginner here, I am not sure if the error is in dictionary files or in nuspell. hunspell doesn't produce any warnings.
[error.log.gz](https://github.com/nuspell/nuspell/files/10184905/error.log.gz)

**Comment by dimztimz** [comment]
Thank you for reporting this bug.

These are possible bugs in the dictionary, please report it there :). The fix is in the warning description, add the command `FLAG UTF-8` somewhere at the top of the the .aff file. Best place is to add it just after `SET UTF-8`. Hunspell does not report anything because it is more stupid, and it simply ignores errors.

**Comment by richo67** [comment]
Changes has been incorporated into sk_SK.aff (not released yet). Your suggested ```FLAG UTF-8```  has not been used, because of information in man page of [hunspell](https://manpages.ubuntu.com/manpages/trusty/en/man4/hunspell.4.html) it breaks hunspell implementation on ARM devices. Owner of sk_SK dictionary has raised [hunspell issue](https://github.com/hunspell/hunspell/issues/896)

Solution was done by using different flag in SFX block identification.
