### ISSUE TITLE
FR: List available spelling languages

### ISSUE THREAD

**Issue by tim-gromeyer** [nuspell/nuspell#128]
Hello,
as you can see in the title I 'm asking for a new feature.  
I think it would not be hard to implement. Just loop over the dic paths, loop over the files, check file extension, store filenames and return them or add them to a vector.

**Comment by dimztimz** [comment]
This already exists. You missed it somehow.

**Comment by tim-gromeyer** [comment]
I must have missed it. I only found `search_dirs_for_one_dict` but that's not exactly what I was searching for ...

**Comment by dimztimz** [comment]
Please read the docs. For starters see the example in readme.

https://github.com/nuspell/nuspell/blob/c0cbfc0a65f040951c41c1e27c02fc58dd588fac/src/nuspell/finder.hxx#L54-L57

**Comment by tim-gromeyer** [comment]
Seems to be (nearly) exactly what I was searching for. Thank you!
