### ISSUE TITLE
Ubuntu/macOS installation

### ISSUE THREAD

**Issue by MayuraVerma** [nuspell/nuspell#131]

**Comment by MayuraVerma** [comment]
Hunspell is distributed part of Ubuntu and macOS

Is Nuspell also being distributed part of Ubuntu and macOS?

or how to install in them?

Is there macport or homebrew?

**Comment by dimztimz** [comment]
Yes, see the home page for details.

**Comment by dimztimz** [comment]
I don't know.

**Comment by MayuraVerma** [comment]
It is listed Nuspell is 3.5x faster than Hunspell. 

For comparison, Does nuspell do everything Hunspell is capable of doing?
Or Hunspell is better than Nuspell in someways or viceversa, in terms of features.

**Comment by dimztimz** [comment]
Nuspell is better.
