### ISSUE TITLE
Question: How to generate wordlist

### ISSUE THREAD

**Issue by MayuraVerma** [nuspell/nuspell#132]
How to generate the complete word list with given dictionary and affix files for a given language.

**Comment by dimztimz** [comment]
You can not do this.

**Comment by MayuraVerma** [comment]
Can we do it in hubspell ?

Or any other way to generate the full list?

**Comment by PanderMusubi** [comment]
This used to be possible in Hunspell until a few years ago, but not anymore. Better is to find the word list from which the dictionary was created. Many of those are also available in Debian or Ubuntu packages.

**Comment by MayuraVerma** [comment]
Thank you.

Is it possible to point to the version that had this feature in Hunspell

The reason, I need this to check the final wordlist Hunspell or Nuspell compiling. If there are unwanted compounded words, then rules can be changed

**Comment by PanderMusubi** [comment]
You have to ask at Hunspell.
