### ISSUE TITLE
compiling v5.1.3 on Debian Trixie does not work due to requirement of old version of Catch2

### ISSUE THREAD

**Issue by alteholz** [nuspell/nuspell#133]
When trying to compile v5.1.3 on Debian Trixie, I got:
(...)
 -- Performing Test COMPILER_HAS_DEPRECATED_ATTR - Success
 CMake Warning at CMakeLists.txt:54 (find_package):
   Could not find a configuration file for package "Catch2" that is compatible
   with requested version "2.3.0".

   The following configuration files were considered but not accepted:

     /usr/lib/cmake/Catch2/Catch2Config.cmake, version: 3.4.0
     /lib/cmake/Catch2/Catch2Config.cmake, version: 3.4.0
(...)

Does one really need version 2.3.0 of Catch2? Would it be possible to also use newer versions?

**Comment by dimztimz** [comment]
I fixed this and published a new version. Try packaging that one.

**Comment by alteholz** [comment]
Great, thanks a lot, I just uploaded v5.1.4
