### ISSUE TITLE
[Question][Unicode range >FFFF

### ISSUE THREAD

**Issue by kovacshviktor** [nuspell/nuspell#136]
@dimztimz 
- Others, questions

Nuspell can work width charsets over FFFF Unicode point?

**Comment by dimztimz** [comment]
Yes it can.

**Comment by kovacshviktor** [comment]
> Yes it can.

I asked it because of that hunspell can't to do it.

Is there a document that describes the syntax of nuspell?

**Comment by dimztimz** [comment]
Yes, please see the Wiki. Generally, it is the same as hunspell.

**Comment by dimztimz** [comment]
Closing this, reopen it if you have more questions.
