### ISSUE TITLE
thread safety?

### ISSUE THREAD

**Issue by tmccombs** [nuspell/nuspell#140]
Is there any thread safety in the API.

In particular:

- is it safe for multiple thrreads to call  Dictionary::load_from_path or Dictionary::load_from_aff_dic?
- Is it safe for multiple threads to call `spell` or `suggest` on the same Dictionary?

Or is it necessary to synchronize all access?

Could that be added to the documentation?

**Comment by dimztimz** [comment]
Each function is fully thread safe toward all arguments that are accessed via const references/pointers, pretty much the usual for any well behaving and modern C++, similar to STL.

> * is it safe for multiple threads to call  `Dictionary::load_from_path` or `Dictionary::load_from_aff_dic`?

Yes, if the objects are different.

> * Is it safe for multiple threads to call `spell` or `suggest` on the same Dictionary?

Yes, these do not modify the object, completely thread-safe.

**Comment by tmccombs** [comment]
Thank you!
