### ISSUE TITLE
Building on FreeBSD

### ISSUE THREAD

**Issue by PanderMusubi** [nuspell/nuspell#15]
There is a small issue building Nuspell  on FreeBSD and other flavors of BSD. When following https://github.com/hunspell/nuspell#building-on-freebsd-netbsd-openbsd-and-bsd-variants the build process stops after:

    autoreconf -vfi
    ./configure --with-warnings CXXFLAGS='-g -O0 -Wall -Wextra'

with this message:

    ...
    checking for Boost headers version >= 1.62.0... yes
    checking for Boost's header version... 1_66
    checking for the toolset name used by Boost for g++... configure: WARNING: could not figure out which toolset name to use for g++
    
    checking boost/system/error_code.hpp usability... yes
    checking boost/system/error_code.hpp presence... yes
    checking for boost/system/error_code.hpp... yes
    checking for the Boost system library... yes
    checking boost/locale.hpp usability... yes
    checking boost/locale.hpp presence... yes
    checking for boost/locale.hpp... yes
    checking for the Boost locale library... no
    configure: error: cannot find the flags to link with Boost locale

and the file `config.log` contains errors such as:

    ...
    configure:18007: g++ -o conftest -g -O0 -Wall -Wextra -I/usr/local/include   conftest.o -lboost_system--mt-1_66  >&5
    /usr/local/bin/ld: cannot find -lboost_system--mt-1_66
    collect2: error: ld returned 1 exit status
    ...
    configure:18296: g++ -o conftest -g -O0 -Wall -Wextra -I/usr/local/include    conftest.o -lboost_locale  -lboost_system >&5
    conftest.o: In function `boost::locale::generator::operator()(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const': /usr/local/include/boost/locale/generator.hpp:202: undefined reference to `boost::locale::generator::generate(std::__c xx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'
    collect2: error: ld returned 1 exit status
    ...

How can this be fixed?

**Comment by PanderMusubi** [comment]
We need an BSD expert, therefore I made a post for help wanted and early involvement for packaging at https://forums.freebsd.org/threads/building-new-spell-checker.66241/

**Comment by cpu82** [comment]
The problem is related to the library naming, if you want to link to the library with multithreading support enabled can be done by adding to `Makefile`, e.g.:
```

LIB_DEPENDS= libboost_thread.so:devel/boost-libs

USES=localbase:ldflags

CONFIGURE_ARGS= --with-boost-incl="${LOCALBASE}/include" \
                                     --with-boost-lib="${LOCALBASE}/lib"
```

**Comment by dimztimz** [comment]
I think its a issue with mixing clang and gcc. clang is default on freebsd, not sure how that g++ appears above.

**Comment by cpu82** [comment]
Both compilers are well supported but as you stated in your comment above, Clang is the default compiler on FreeBSD:

**Comment by PanderMusubi** [comment]
The installation of build dependencies is at the moment

    sudo pkg install -y bash autoconf automake libtool libiconv icu gcc wget \
                    boost-libs

If we want to use the default (clang) what should change in the install instructions?

**Comment by dimztimz** [comment]
Dont use gcc

**Comment by cpu82** [comment]
@PanderMusubi: do you have created the `nuspell` port for FreeBSD? I want to take a look.

@dimztimz: it's correct. Don't pull `gcc` as a dependency.

**Comment by PanderMusubi** [comment]
I now did `sudo pkg delete gcc gcc6` and the build results in

    ...
    checking for boost/locale.hpp... yes
    checking for the Boost locale library... (cached) yes
    ./configure: 18441: Syntax error: word unexpected (expecting ")")

Any pointers on how to go to the next step?

**Comment by cpu82** [comment]
Add `USES=autoreconf` instead of `USES=autoconf`.

**Comment by PanderMusubi** [comment]
Adding that to the top of `configure.ac` gave the same error. @cpu82 could you try build it? Just use the latest commit of this repo.

**Comment by jbeich** [comment]
> ```./configure: 18441: Syntax error: word unexpected (expecting ")")```

Install `pkgconf` then re-run `autoreconf` to expand `PKG_CHECK_MODULES` macro defined in /usr/local/share/aclocal/pkg.m4.

**Comment by jbeich** [comment]
Doesn't really build on FreeBSD. Maybe @bapt knows what happened to `__STDC_ISO_10646__` implementation mentioned in [2016Q4 quarterly report](https://www.freebsd.org/news/status/report-2016-10-2016-12.html#The-FreeBSD-Core-Team).
```
In file included from locale_utils.cxx:24:
In file included from ./locale_utils.hxx:27:
In file included from /usr/local/include/boost/locale/encoding_utf.hpp:12:
/usr/local/include/boost/locale/encoding_errors.hpp:44:51: error: implicit instantiation of undefined template
      'std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >'
                invalid_charset_error(std::string charset) :
                                                  ^
/usr/include/c++/v1/iosfwd:193:32: note: template is declared here
    class _LIBCPP_TEMPLATE_VIS basic_string;
                               ^
locale_utils.cxx:41:2: error: "Platform has poor Unicode support. wchar_t must be Unicode."
#error "Platform has poor Unicode support. wchar_t must be Unicode."
 ^
2 errors generated.
```
https://github.com/hunspell/nuspell/blob/1bd79b9ee8e7de6459247e95c4a502be8b2286e0/src/nuspell/locale_utils.cxx#L40-L42

**Comment by cpu82** [comment]
```
locale_utils.cxx:41:2: error: "Platform has poor Unicode support. wchar_t must be Unicode."
#error "Platform has poor Unicode support. wchar_t must be Unicode."
 ^
```
Try the following patch
```
--- src/nuspell/locale_utils.cxx.orig	2018-06-12 10:24:19 UTC
+++ src/nuspell/locale_utils.cxx
@@ -36,7 +36,7 @@
 #include <intrin.h>
 #endif
 
-#if !defined(_WIN32)
+#if !defined(_WIN32) && !defined(__FreeBSD__)
 #if !defined(__STDC_ISO_10646__) || defined(__STDC_MB_MIGHT_NEQ_WC__)
 #error "Platform has poor Unicode support. wchar_t must be Unicode."
 #endif
```

**Comment by cpu82** [comment]
Again it fails to build as follows
```
make[5]: "/usr/ports/textproc/nuspell/work/nuspell-1bd79b9/tests/v1cmdline/Makefile" line 1472: Need an operator
make[5]: Fatal errors encountered -- cannot continue
make[5]: stopped in /usr/ports/textproc/nuspell/work/nuspell-1bd79b9/tests/v1cmdline
*** [all-recursive] Error code 1
```

**Comment by jbeich** [comment]
> ```tests/v1cmdline/Makefile line 1472: Need an operator```

BSD make doesn't support [`override` directive](https://www.gnu.org/software/make/manual/html_node/Override-Directive.html#Override-Directive) but can use [`.MAKEFLAGS` target](https://www.freebsd.org/cgi/man.cgi?query=make&sektion=1&n=1#SPECIAL%09TARGETS) to override variables specified on command line. No point avoiding `gmake` dependency then.

**Comment by jbeich** [comment]
> ```diff
> -#if !defined(_WIN32)
> +#if !defined(_WIN32) && !defined(__FreeBSD__)
> ```

With the hack `gmake check` showed few failures, in non-UTF-8 locales.

```
FAIL: ch.catch 402 - isupper('\xC8', loc) for: false # icu ctype facets
FAIL: ch.catch 404 - islower('\xE8', loc) for: false # icu ctype facets
```

**Comment by dimztimz** [comment]
Thank you both for the contributions, this patch 438e6e5ac6b18c3128b29c6538f4efea5fcb9b43 should be minimal for FreeBSD build to finish.

**Comment by cpu82** [comment]
I have created a nuspell port for FreeBSD.

**Comment by dimztimz** [comment]
We recently updated Cmake build system and released v2.2.0 with bunch of other improvements. See the [releases page](https://github.com/nuspell/nuspell/releases) If you are willing, would you update the FreeBSD port?

With CMake things go much smoother.

**Comment by dimztimz** [comment]
Noticed the FreeBSD port is already updated. Thanks.

**Comment by PanderMusubi** [comment]
@jbeich @cpu82 , please see https://github.com/cpu82/nuspell/issues/2
