### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [nuspell/nuspell#27]
[An extra null pointer check is not needed in functions](https://stackoverflow.com/questions/18775608/free-a-null-pointer-anyway-or-check-first "Free a null pointer anyway or check first?") like the following.
- [HunspellImpl](https://github.com/nuspell/nuspell/blob/45d383c0e2f25e4ea48ee8efeca53c2bb51a3510/src/hunspell/hunspell.cxx#L192 "Constructor for HunspellImpl")
- [Hunzip](https://github.com/nuspell/nuspell/blob/45d383c0e2f25e4ea48ee8efeca53c2bb51a3510/src/hunspell/hunzip.cxx#L170 "Destructor for Hunzip")
- [SuggestMgr](https://github.com/nuspell/nuspell/blob/45d383c0e2f25e4ea48ee8efeca53c2bb51a3510/src/hunspell/suggestmgr.cxx#L137 "Destructor for SuggestMgr")

**Comment by PanderMusubi** [comment]
Thanks for notificing, but these code we have now only for verification purposes. In order to track changes from its upstream, we do not improve or change this code. Eventually, it will disappear from our code base.
