### ISSUE TITLE
Improve exception safety with smart pointers

### ISSUE THREAD

**Issue by elfring** [nuspell/nuspell#28]
Would you like to wrap any pointer data members with the class template “[std::unique_ptr](https://en.wikipedia.org/wiki/Smart_pointer#unique_ptr "Description for the usage of smart pointers")”?

Update candidates:
- [HunspellImpl class](https://github.com/nuspell/nuspell/blob/45d383c0e2f25e4ea48ee8efeca53c2bb51a3510/src/hunspell/hunspell.cxx#L166)
- [myopen() function](https://github.com/nuspell/nuspell/blob/45d383c0e2f25e4ea48ee8efeca53c2bb51a3510/src/hunspell/csutil.cxx#L116)

**Comment by PanderMusubi** [comment]
Thanks for notificing, but these code we have now only for verification purposes. In order to track changes from its upstream, we do not improve or change this code. Eventually, it will disappear from our code base.
