### ISSUE TITLE
How to build nuspell as a shared library?

### ISSUE THREAD

**Issue by ariasuni** [nuspell/nuspell#29]
I tried to compile nuspell on Linux as a shared library to replace Hunspell systemd-wide, but I only managed to obtain a `.a` file.

| key                                       | value |
|-------------------------------------------|-------|
| Operating system, distribution, version = | Arch Linux |
| Nuspell version                           | 2.1.0 |

**Comment by dimztimz** [comment]
Thank you for your interest in Nuspell.

You can not just replace the built hunspell shared library with nuspell shared library, the API is different. One has to specifically use Nuspell.

**Comment by ariasuni** [comment]
I was mislead by the term «drop-in replacement». Still, I’d like to provide a package of Nuspell as a shared library.

**Comment by PanderMusubi** [comment]
It will be a drop-in replacement. We simply haven't added building of the drop-in shared library yet. First we need to optimize and fully complete the spell checking and suggestion functionality before we do that.

Functionality is almost complete and planned optimizations will bring a lot of speed-up. For most languages, Nuspell already surpasses other spell checkers, but we want it to have benefits for all specific options before we offer a drop-in shared library.

**Comment by PanderMusubi** [comment]
What kind of package would you like to provide? A .deb for Debian and Ubuntu?

**Comment by ariasuni** [comment]
I want to provide a package for Arch Linux via AUR. I suppose I should do like the package [`boost`](https://www.archlinux.org/packages/extra/x86_64/boost/) and provides the headers and the `.a`.

**Comment by PanderMusubi** [comment]
You can have a look at how Hunspell has been packaged. For Debian/Ubuntu for Nuspell, it will result in:
* `libnuspell-dev` containing header files and development libraries (`.a` and `.so`)
* `libnuspell-2.1-0` containing the runtime shared library (`.so` which is not available yet)
* `nuspell` containing the command line tool `/usr/bin/nuspell`

Since we do not have special tools, there will (for now) not be a package called `nuspell-tools`. Not sure how this translates to Arch Linux. do you?

**Comment by PanderMusubi** [comment]
Dependencies are on `libboost-locale` and `libicu`and the needed C libraries.

**Comment by ariasuni** [comment]
Here it is: https://aur.archlinux.org/packages/nuspell/

**Comment by PanderMusubi** [comment]
Thanks! There are some upcoming improvements. Will let you know when they have landed. They will also affect your package, at least one dependency can be dropped. We are also working on a Debian package, so any improvements from that process I will share with you too.

**Comment by dimztimz** [comment]
The changes landed https://github.com/nuspell/nuspell/releases/tag/v2.2.0 . Major update is that we  use CMake to build which nicely supports shared libraries by specifying https://cmake.org/cmake/help/v3.0/variable/BUILD_SHARED_LIBS.html on the command line.

Close this issue when you are done with it.

**Comment by dimztimz** [comment]
One more thing, in the package, update the licenses to only LGPL3+. There is no three license.

**Comment by ariasuni** [comment]
I forgot to answer but thanks, I updated the license to LGPL3+. :)

**Comment by dimztimz** [comment]
There are few more things that you can do in the package.

1. Enable release mode by adding the argument `-DCMAKE_BUILD_TYPE=Release` in the cmake invocation.
2. AFAIK, `-DCMAKE_INSTALL_LIBDIR=/usr/lib` is redundant, it is not needed, as INSTALL_PREFIX already does the job. Test and see.

**Comment by ariasuni** [comment]
I added `-DCMAKE_BUILD_TYPE=Release`, thanks!

However, I must use `-DCMAKE_INSTALL_LIBDIR=/usr/lib` because otherwise it defaults to `/usr/lib64` which is not what we want on Arch Linux.

**Comment by dimztimz** [comment]
Hello @ariasuni . I think i found one minor bug in the dependencies of the Arch package.

Currently you have this:

    depends=('boost-libs' 'icu')
    makedepends=('boost' 'catch2' 'cmake' 'ruby-ronn')

You should make the whole "boost", and not just "boost-libs" as run-time dependency. It's not exactly run-time, but that should be changed because the Nuspell C++ public headers depend on Boost C++ headers.

**Comment by ariasuni** [comment]
It’s done! [link to commit](https://aur.archlinux.org/cgit/aur.git/commit/PKGBUILD?h=nuspell&id=a59f092eb9c2454c1c6195d2cffda8144c838cfe)
