### ISSUE TITLE
New dictionary package Latvian results in core dump 

### ISSUE THREAD

**Issue by PanderMusubi** [nuspell/nuspell#30]
Reported on Ubuntu 18.10 with Nuspell 2.2. Latvian dictionary recently got refactored moved from `myspell-lv` (which worded) to `hunspell-lv` version 1.3.0-2. This new package results in a core dump with the following output:

    terminate called after throwing an instance of 'std::invalid_argument'
      what():  closing bracket has no matching opening bracket
    Aborted (core dumped)

Either a fix is needed upstream in this dictionary or Nuspell should be able to handle whatever is causing this error. (Hunspell version 1.6.2 can load this dictionary.)

**Comment by dimztimz** [comment]
This is an actual error in the dictionary which is properly reported. Hunspell loads because it ignores errors. The error is in the lv_LV.aff, line 1609.

    SFX F  īt  a/]| |^cz]īt   is:0xttv

A pipe character is used instead of opening bracket. What we can do is improve the error reporting.

**Comment by dimztimz** [comment]
Internally, the type of the thrown exception should be changed to a type that inherits from runtime_exception. That exception can be then caught and then reported.

**Comment by dimztimz** [comment]
This should be reported upstream.

**Comment by PanderMusubi** [comment]
Contacted the author via email and have a temporary fix in out test scripts.

**Comment by PanderMusubi** [comment]
Author replied he will work on it during Easter

**Comment by PanderMusubi** [comment]
Fixed in https://sourceforge.net/projects/openoffice-lv/ version 1.4.0

Keeping this open to add the Debian package software upgrade request.

**Comment by dimztimz** [comment]
Is this fixed?

**Comment by dimztimz** [comment]
Seems like it has landed in Debian testing https://packages.debian.org/bullseye/hunspell-lv . Closing.

**Comment by PanderMusubi** [comment]
Landed in testing a few weeks after I verified it was fixed upstream. I'm also in contact with Agustin Martin Domingo on those dict upgrades once in a while. This is indeed closed.
