### ISSUE TITLE
Errors while parsing updated dictionary for Catalan language

### ISSUE THREAD

**Issue by PanderMusubi** [nuspell/nuspell#31]
Reported on Ubuntu 18.10 with Nuspell 2.2. Catalan dictionary 'hunspell-ca' version '3.0.3+repack1-1'. The output is:

    INFO: I/O locale name=en_US.UTF-8, lang=en, country=US, enc=utf-8
    INFO: Dictionary path=../1-support/files/hunspell-ca/3.0.3+repack1-1/usr/share/hunspell/ca.{dic,aff}
    Nuspell error: missing flags in line 675
    Nuspell error: could not parse affix file line 675: SFX 00 r t/ ar
    Nuspell error: missing flags in line 676
    Nuspell error: could not parse affix file line 676: SFX 00 r da/ ar
    Nuspell error: missing flags in line 677
    Nuspell error: could not parse affix file line 677: SFX 00 r ts/ ar
    Nuspell error: missing flags in line 678
    Nuspell error: could not parse affix file line 678: SFX 00 r des/ ar
    Nuspell error: missing flags in line 679
    Nuspell error: could not parse affix file line 679: SFX 00 ar o/ ar
    Nuspell error: missing flags in line 680
    Nuspell error: could not parse affix file line 680: SFX 00 ar e/ ar
    Nuspell error: missing flags in line 681
    Nuspell error: could not parse affix file line 681: SFX 00 ar 0/ ar
    Nuspell error: missing flags in line 682
    Nuspell error: could not parse affix file line 682: SFX 00 ar es/ ar
    Nuspell error: missing flags in line 683
    Nuspell error: could not parse affix file line 683: SFX 00 r 0/ ar
    Nuspell error: missing flags in line 684
    Nuspell error: could not parse affix file line 684: SFX 00 ar em/ ar
    Nuspell error: missing flags in line 685
    Nuspell error: could not parse affix file line 685: SFX 00 r m/ ar
    Nuspell error: missing flags in line 686
    Nuspell error: could not parse affix file line 686: SFX 00 ar eu/ ar
    Nuspell error: missing flags in line 687
    Nuspell error: could not parse affix file line 687: SFX 00 r u/ ar
    Nuspell error: missing flags in line 688
    Nuspell error: could not parse affix file line 688: SFX 00 ar en/ ar
    Nuspell error: missing flags in line 689
    Nuspell error: could not parse affix file line 689: SFX 00 r va/ ar
    Nuspell error: missing flags in line 690
    Nuspell error: could not parse affix file line 690: SFX 00 r ves/ ar
    Nuspell error: missing flags in line 691
    Nuspell error: could not parse affix file line 691: SFX 00 r va/ ar
    Nuspell error: missing flags in line 692
    Nuspell error: could not parse affix file line 692: SFX 00 ar àvem/ ar
    Nuspell error: missing flags in line 693
    Nuspell error: could not parse affix file line 693: SFX 00 ar àveu/ ar
    Nuspell error: missing flags in line 694
    Nuspell error: could not parse affix file line 694: SFX 00 r ven/ ar
    Nuspell error: missing flags in line 695
    Nuspell error: could not parse affix file line 695: SFX 00 ar í/ ar
    Nuspell error: missing flags in line 696
    Nuspell error: could not parse affix file line 696: SFX 00 r res/ ar
    Nuspell error: missing flags in line 697
    Nuspell error: could not parse affix file line 697: SFX 00 ar à/ ar
    Nuspell error: missing flags in line 698
    Nuspell error: could not parse affix file line 698: SFX 00 ar àrem/ ar
    Nuspell error: missing flags in line 699
    Nuspell error: could not parse affix file line 699: SFX 00 ar àreu/ ar
    Nuspell error: missing flags in line 700
    Nuspell error: could not parse affix file line 700: SFX 00 r ren/ ar
    Nuspell error: missing flags in line 701
    Nuspell error: could not parse affix file line 701: SFX 00 r ré/ ar
    Nuspell error: missing flags in line 702
    Nuspell error: could not parse affix file line 702: SFX 00 r ràs/ ar
    Nuspell error: missing flags in line 703
    Nuspell error: could not parse affix file line 703: SFX 00 r rà/ ar
    Nuspell error: missing flags in line 704
    Nuspell error: could not parse affix file line 704: SFX 00 r rem/ ar
    Nuspell error: missing flags in line 705
    Nuspell error: could not parse affix file line 705: SFX 00 r reu/ ar
    Nuspell error: missing flags in line 706
    Nuspell error: could not parse affix file line 706: SFX 00 r ran/ ar
    Nuspell error: missing flags in line 707
    Nuspell error: could not parse affix file line 707: SFX 00 r ria/ ar
    Nuspell error: missing flags in line 708
    Nuspell error: could not parse affix file line 708: SFX 00 r ries/ ar
    Nuspell error: missing flags in line 709
    Nuspell error: could not parse affix file line 709: SFX 00 r ria/ ar
    Nuspell error: missing flags in line 710
    Nuspell error: could not parse affix file line 710: SFX 00 r ríem/ ar
    Nuspell error: missing flags in line 711
    Nuspell error: could not parse affix file line 711: SFX 00 r ríeu/ ar
    Nuspell error: missing flags in line 712
    Nuspell error: could not parse affix file line 712: SFX 00 r rien/ ar
    Nuspell error: missing flags in line 713
    Nuspell error: could not parse affix file line 713: SFX 00 ar e/ ar
    Nuspell error: missing flags in line 714
    Nuspell error: could not parse affix file line 714: SFX 00 ar i/ ar
    Nuspell error: missing flags in line 715
    Nuspell error: could not parse affix file line 715: SFX 00 ar es/ ar
    Nuspell error: missing flags in line 716
    Nuspell error: could not parse affix file line 716: SFX 00 ar is/ ar
    Nuspell error: missing flags in line 717
    Nuspell error: could not parse affix file line 717: SFX 00 ar e/ ar
    Nuspell error: missing flags in line 718
    Nuspell error: could not parse affix file line 718: SFX 00 ar i/ ar
    Nuspell error: missing flags in line 719
    Nuspell error: could not parse affix file line 719: SFX 00 ar em/ ar
    Nuspell error: missing flags in line 720
    Nuspell error: could not parse affix file line 720: SFX 00 ar eu/ ar
    Nuspell error: missing flags in line 721
    Nuspell error: could not parse affix file line 721: SFX 00 ar en/ ar
    Nuspell error: missing flags in line 722
    Nuspell error: could not parse affix file line 722: SFX 00 ar in/ ar
    Nuspell error: missing flags in line 723
    Nuspell error: could not parse affix file line 723: SFX 00 ar és/ ar
    Nuspell error: missing flags in line 724
    Nuspell error: could not parse affix file line 724: SFX 00 r ra/ ar
    Nuspell error: missing flags in line 725
    Nuspell error: could not parse affix file line 725: SFX 00 ar às/ ar
    Nuspell error: missing flags in line 726
    Nuspell error: could not parse affix file line 726: SFX 00 ar essis/ ar
    Nuspell error: missing flags in line 727
    Nuspell error: could not parse affix file line 727: SFX 00 r res/ ar
    Nuspell error: missing flags in line 728
    Nuspell error: could not parse affix file line 728: SFX 00 r ssis/ ar
    Nuspell error: missing flags in line 729
    Nuspell error: could not parse affix file line 729: SFX 00 ar esses/ ar
    Nuspell error: missing flags in line 730
    Nuspell error: could not parse affix file line 730: SFX 00 r sses/ ar
    Nuspell error: missing flags in line 731
    Nuspell error: could not parse affix file line 731: SFX 00 ar és/ ar
    Nuspell error: missing flags in line 732
    Nuspell error: could not parse affix file line 732: SFX 00 r ra/ ar
    Nuspell error: missing flags in line 733
    Nuspell error: could not parse affix file line 733: SFX 00 ar às/ ar
    Nuspell error: missing flags in line 734
    Nuspell error: could not parse affix file line 734: SFX 00 ar éssim/ ar
    Nuspell error: missing flags in line 735
    Nuspell error: could not parse affix file line 735: SFX 00 ar àrem/ ar
    Nuspell error: missing flags in line 736
    Nuspell error: could not parse affix file line 736: SFX 00 ar àssim/ ar
    Nuspell error: missing flags in line 737
    Nuspell error: could not parse affix file line 737: SFX 00 ar éssem/ ar
    Nuspell error: missing flags in line 738
    Nuspell error: could not parse affix file line 738: SFX 00 ar àssem/ ar
    Nuspell error: missing flags in line 739
    Nuspell error: could not parse affix file line 739: SFX 00 ar éssiu/ ar
    Nuspell error: missing flags in line 740
    Nuspell error: could not parse affix file line 740: SFX 00 ar àreu/ ar
    Nuspell error: missing flags in line 741
    Nuspell error: could not parse affix file line 741: SFX 00 ar àssiu/ ar
    Nuspell error: missing flags in line 742
    Nuspell error: could not parse affix file line 742: SFX 00 ar ésseu/ ar
    Nuspell error: missing flags in line 743
    Nuspell error: could not parse affix file line 743: SFX 00 ar àsseu/ ar
    Nuspell error: missing flags in line 744
    Nuspell error: could not parse affix file line 744: SFX 00 ar essin/ ar
    Nuspell error: missing flags in line 745
    Nuspell error: could not parse affix file line 745: SFX 00 r ren/ ar
    Nuspell error: missing flags in line 746
    Nuspell error: could not parse affix file line 746: SFX 00 r ssin/ ar
    Nuspell error: missing flags in line 747
    Nuspell error: could not parse affix file line 747: SFX 00 ar essen/ ar
    Nuspell error: missing flags in line 748
    Nuspell error: could not parse affix file line 748: SFX 00 r ssen/ ar

Either a fix is needed upstream in this dictionary or Nuspell should be able to handle whatever is causing this error. (Hunspell version 1.6.2 can load this dictionary without errors.)

Similar errors are reported for the `ca_ES-valencia` dictionary in the same Debian package.

**Comment by dimztimz** [comment]
The error is no flags after slash in the aff file while parsing affixes. This can be turned into a warning.
