### ISSUE TITLE
Error while parsing updated Aragonese dictionary

### ISSUE THREAD

**Issue by PanderMusubi** [nuspell/nuspell#32]
Reported on Ubuntu 18.10 with Nuspell 2.2. Aragonese dictionary 'hunspell-an' version 0.2-3'. The output is:

    INFO: I/O locale name=en_US.UTF-8, lang=en, country=US, enc=utf-8
    INFO: Dictionary path=../1-support/files/hunspell-an/0.2-3/usr/share/hunspell/an_ES.{dic,aff}
    Nuspell error: missing flags in line 4193

Either a fix is needed upstream in this dictionary or Nuspell should be able to handle whatever is causing this error. (Hunspell version 1.6.2 can load this dictionary without errors.)

**Comment by dimztimz** [comment]
The error is no flags after slash in the dic file. This can be turned into a warning.
