### ISSUE TITLE
Binary dictionary

### ISSUE THREAD

**Issue by MayuraVerma** [nuspell/nuspell#34]
The issues can be of three types (delete two rows and leave only one):

- Others, questions

# Reporting bugs

When reporting a bug you must tell us the state of your system and the
steps to reproduce the bug. For the state please specify the following:

| key                                       | value |
|-------------------------------------------|-------|
| Operating system, distribution, version = |  Any     |
| Nuspell version                         = | 2.2  |
| Dictionary, package name, version       = | Any      |
| Command-line tool or GUI application    = |  Nul     |

# Other issues

Can we create a binary dictionary for distribution?
If yes, can the binary dictionary be able to convert to UTF-8 format back?
How to create binary version of dictionary?
Is there is any performance loss in using binary dictionary?

**Comment by PanderMusubi** [comment]
@MayuraVerma thanks for your question. We will discuss this and let you know here.

**Comment by dimztimz** [comment]
Thank you for your interest in Nuspell. There is no binary dictionary. There is only one file format for dictionaries and it is text-based.

**Comment by MayuraVerma** [comment]
If the dictionary is text based. Then it can be copied by anybody and re-distribute in their name. Is there a way to encrypt the dictionary?

**Comment by dimztimz** [comment]
> If the dictionary is text based. Then it can be copied by anybody and re-distribute in their name.

You have wrong assumptions about binary files. Those too can be copied by anybody and can be re-distributed in other's name.

> Is there a way to encrypt the dictionary?

Yes, use any common tool for encryption like GnuPG.

**Comment by MayuraVerma** [comment]
can there an example to implement nuspell with encrypted dictionary?
