### ISSUE TITLE
Homebrew build options have been removed

### ISSUE THREAD

**Issue by jeanm** [nuspell/nuspell#37]
(First of all congrats on the project – something like this was long overdue! Excited to see what you come up with for the next version)

Your instructions in the README for building on macOS are unfortunately no longer working. Due to Homebrew [removing build options](https://github.com/Homebrew/homebrew-core/issues/31510), the command `brew install boost --with-icu4c` fails with:
```
Error: invalid option: --with-icu4c
```

Doing just `brew install boost` and proceeding as usual will lead, as expected, to a cmake failure:
```
-- The following ICU libraries were not found:
--   uc (required)
--   data (required)
CMake Error at /usr/local/Cellar/cmake/3.14.4/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
if [ -f ~/.bashrc ]; then
  Failed to find all ICU components (missing: ICU_INCLUDE_DIR ICU_LIBRARY
  _ICU_REQUIRED_LIBS_FOUND)
Call Stack (most recent call first):
if [ -f ~/.bashrc ]; then
  /usr/local/Cellar/cmake/3.14.4/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  /usr/local/Cellar/cmake/3.14.4/share/cmake/Modules/FindICU.cmake:324 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:9 (find_package)


-- Configuring incomplete, errors occurred!
```

(I'm on macOS 10.14.4 and I'm trying to build master, but I doubt that's relevant)

**Comment by MichaelVoelkel** [comment]
Why closed without comment? Exactly my problem

**Comment by dimztimz** [comment]
> Why closed without comment? Exactly my problem

The bug is fixed, please look about 3 centimeters above your comment. It even says the git commit in which the bug is fixed.
