### ISSUE TITLE
functioning of morphological fields and other things

### ISSUE THREAD

**Issue by mtrevisan** [nuspell/nuspell#41]
# Other issues

Since I found no documentation whatsoever on hunspell format, and contacting László Németh for help is quite impossible, I would like to ask you how morphological fields works.

In particular, the affix rules in the .aff file can have "po:" (part-of-speech) fields? How "is:" and "ts:" interacts one with another? are there any other interactions between composition of other fields? can a morphological field be repeated as in "o	po:noun is:singular is:femenine is:non_enumerable"?

I found in some place that:
"Derivational Suffix: stemming doesn't remove derivational suffixes (morphological generation depends on the order of the suffix fields)" >> that means that every other non-derivational suffixes are removed? what are the derivational suffixes?
"Inflectional Suffix: all inflectional suffixes are removed by stemming (morphological generation depends on the order of the suffix fields)" >> what are these inflectional suffixes other than "is:"?
"Terminal Suffix: inflectional suffix fields removed by additional (not terminal) suffixes, useful for zero morphemes and affixes removed by splitting rules" >> what are these non-terminal suffixes? all but "ts:"?

Regarding REP: are they applied just once? or a word can have multiple REP substitutions?

Thank you.

**Comment by PanderMusubi** [comment]
Thanks for your question. Morphological information in Hunspell is used for `analyze` and `stem`, two functions which are currently out of scope for Nuspell, see also https://github.com/nuspell/nuspell/blob/master/src/nuspell/aff_data.hxx#L99

I can however answer some of your questions. If you have multiple values for one key, you can add this with a `+`, for example `is:femenine is:non_enumerable` would become ` is:femenine+non_enumerable`. For more info on it all interacts, please see the Hunspell source code. You can also have a look at https://github.com/hunspell/mythes regarding morphological fields.

Regarding `REP`, search for `reps` and `replacements` in https://github.com/nuspell/nuspell/tree/master/src/nuspell to see where these are used.

I hope this answers your questions.

**Comment by mtrevisan** [comment]
Thank you!

**Comment by PanderMusubi** [comment]
Why did you reopen this issue?

**Comment by mtrevisan** [comment]
I thought maybe it wasn't my duty to close the issue... but if you think I
could do, if there is no problem, I'll close it again.
