### ISSUE TITLE
dictionary issues in hunspell

### ISSUE THREAD

**Issue by jnweiger** [nuspell/nuspell#42]
I've recently run into issues with the german dictionary of hunspell, as integrated in LibeOffice. 
I am probably here in the wrong place, asking for help with e.g. things like this:
![photo_2020-01-20_01-04-35(1)](https://user-images.githubusercontent.com/1108546/73590600-91f1da00-44e4-11ea-8e8c-3a13977b860e.jpg)
![photo_2020-01-20_01-04-55(1)](https://user-images.githubusercontent.com/1108546/73590601-928a7080-44e4-11ea-8824-cd791dff9af5.jpg)
I also saw a suggestion to replace https in URLs with http.

Which direction should I go, to contribute to the german dictionary?

**Comment by PanderMusubi** [comment]
It depends which Hunspell package with German dictionary you have installed and which you are using. The packages what you might be using could be `hunspell-de-de` or `hunspell-de-de-frami`. The website of the first to contribute to is https://www.j3e.de/ispell/igerman98/ The `-frami` simply has some changes on top of that according to the 2006 spelling reform.

For more information, see also https://wiki.documentfoundation.org/Language_support_of_LibreOffice and https://www.openthesaurus.de/
