### ISSUE TITLE
LGPL "v3 only" or "v3 or later"?

### ISSUE THREAD

**Issue by hartwork** [nuspell/nuspell#51]
Dear nuspell developers,

I'm aware that we don't have LGPL v4; yet I noticed an inconsistency:
- code headers like https://github.com/nuspell/nuspell/blob/master/src/nuspell/aff_data.cxx say `either version 3 of the License, or (at your option) any later version`
- readme says `LGPL v3`, i.e. no `or later`
- website https://nuspell.github.io/ says `LGPL` and does not mention versions at all.

I think it would be nice to have all places say "v3 or later" consistently, provided that that's the actual license. What do you think?

Thanks and best, Sebastian

**Comment by PanderMusubi** [comment]
Dear Sebastian, please have a look at https://github.com/nuspell/nuspell/blob/debian/debian/copyright which is available since yesterday. It holds all the detailed information. Let me know if you have any remaining questions after reading it. We will have a look on how to mention this on our website.

**Comment by hartwork** [comment]
Hi @PanderMusubi , thanks for the link to that file!
I learned two things from that file:
- It does not mention "LGPL-3 or later" anywhere as e.g. https://github.com/nuspell/nuspell/blob/master/src/nuspell/aff_data.cxx does so it's out of sync with code headers to some extent and it would be cool to have that conflict resolved one way or another.
- It shows mixing of (L)GPL-2 and LGPL-3 which I understood to be incompatible. It would be nice to understand why that incompatibility does not affect Nuspell.

Happy to learn what I'm missing.

**Comment by dimztimz** [comment]
The notice in the source files is the most relevant. Hunspell also says **LGPL v2.1 or later**. As for the debian file, don't look at it.  I guess that should be fixed too. Look the C++ source files.

**Comment by hartwork** [comment]
> Hunspell also says **LGPL v2.1 or later**.

That's great, found it in the files now.

> As for the debian file, don't look at it. I guess that should be fixed too. 

Yes, let's fix the `debian/copyright` file.

If I look at all `.cxx` and `.hxx` files I find exactly three buckets:
- MPL 1.1 or GPL "2 or later" or LGPL "2.1 or later"
- LGPL 2.1 (only) and MPL/GPL/LGPL tri-license statements mutually contradicting each other in the same file — files `src/hunspell/phonet.[ch]xx`; seems harmless (see below) but broken
- LGPL 3 or later

So the headers of `src/hunspell/phonet.[ch]xx` need fixing too, they need to have their own changelog applied to the header text above.

**Comment by dimztimz** [comment]
The first 2 buckets are from Hunspell, and we do not even use it by the library Nuspell. It is used only for testing. After `make install`, the end user never sees the testing bits, so let's not complicate it much.

Thanks for pointing the initial issue.

**Comment by dimztimz** [comment]
https://github.com/gentoo/gentoo/commit/feb6ac99da13a8ebfefb3740976520a874bd8383 this is wrong.

**Comment by PanderMusubi** [comment]
The detailed copyright was made by a Debian package maintainer, but he didn't know that old code was not used in what eventueally lands in the installable packages.

**Comment by dimztimz** [comment]
I fixed this in the readme and on the website and the debian file. @hartwork please put only LGPLv3+ in your port. Big thanks for doing it. Closing for now.

**Comment by hartwork** [comment]
> The first 2 buckets are from Hunspell, and we do not even use it by the library Nuspell. It is used only for testing. After `make install`, the end user never sees the testing bits, so let's not complicate it much.

That's good to know (and not easy to figure out by oneself). I suggest to move `src/parsers/` and `src/tools/` below `src/hunspell/` — the current directory structure miscommunicate that these things would not belong to hunspell.

> [gentoo/gentoo@feb6ac9](https://github.com/gentoo/gentoo/commit/feb6ac99da13a8ebfefb3740976520a874bd8383) this is wrong.

Let's avoid "this is wrong" without arguments in the future please.

I have understood why you considered wrong by myself now and https://github.com/gentoo/gentoo/commit/a87af8d202297948dc1f6a0e27abc8c33eca7363 should be more right in that regard.

> The detailed copyright was made by a Debian package maintainer, but he didn't know that old code was not used in what eventueally lands in the installable packages.

It's not his fault in my eyes. That should be made documented and obvious, especially to people who care about licensing like him and me.

> I fixed this in the readme and on the website and the debian file. @hartwork please put only LGPLv3+ in your port.

I did something close, see https://github.com/gentoo/gentoo/commit/a87af8d202297948dc1f6a0e27abc8c33eca7363 .

> Big thanks for doing it. Closing for now.

Just for the record, this is the second time a ticket is closed in my face with parts unfixed that I consider broken and no new tickets created. You're not exactly making me want to start pull requests, if that's not obvious.
