### ISSUE TITLE
[master] Two half-working scripts clang-format.sh?

### ISSUE THREAD

**Issue by hartwork** [nuspell/nuspell#52]
Hi!

I came across two files called `clang-format.sh` in here:

```console
# cat clang-format.sh 
cd $(dirname "$0")
clang-format -style=file -i src/nuspell/*.[ch]xx tests/*.[ch]xx

# cat src/nuspell/clang-format.sh 
clang-format -style=file -i *.[ch]xx
```

To my surprise
- do not come with a portable (or any) shebang line like `#! /usr/bin/env bash`
- continue despite failure of `cd $(dirname "$0")` —due to lack of quoting—
- …in case that directory name happens to contain one or more spaces.

Does that mean these scripts are not used in practice?

**Comment by PanderMusubi** [comment]
Thanks for your watchful eye. They are used but haven't been provided with a shebang yet. If you want, could you make a PR where `#!/usr/bin/env sh` is added and the script conforms to the conventions for that shell?

**Comment by dimztimz** [comment]
According to POSIX not having shebang is the most portable way. Such script is treated as POSIX shell script.

**Comment by hartwork** [comment]
@dimztimz could you please provide an authoritative link "for proof", e.g. something on pubs.opengroup.org?

It would explain, why I was able to run `./clang-format.sh` in Bash. 
If it's true, only the call to `cd` needs extra quoting, I guess?

I have a feeling though it might (a) not be true or (b) not 100% practical, e.g. Python says `Exec format error` when I try to execute a file like that using standard `subprocess.call`:
```console
# cd "$(mktemp -d)"
# echo 'set -x; echo "$@"' > echo.sh
# chmod a+x echo.sh 
# ./echo.sh foo bar
++ echo foo bar
foo bar
# python -c 'import subprocess; subprocess.call(["./echo.sh", "foo", "bar"])'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib64/python3.6/subprocess.py", line 287, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib64/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/usr/lib64/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: './echo.sh'
```

Am I missing something?

**Comment by dimztimz** [comment]
This script is not used in the build process. It is merely a convince for the developers writing the source code, and that's all. Clmag format is a tool that reformat source files, keeps the indentation clean.

Its not meant for downstream users at all.

**Comment by hartwork** [comment]
We're probably about to collectively learn something about POSIX here that will be relevant to all of our futures in the *nix world. Why close this ticket? Also, if they're not meant for user consumption, let's delete them?

**Comment by hartwork** [comment]
PS: Invocation from C works:
```console
# cat main.c 
#include <unistd.h>
#include <errno.h>
#include <string.h>
#include <stdio.h>
#include <stdlib.h>

int main() {
        char * const argv[] = {"./echo.sh", "foo", "bar", NULL};
        execvp(argv[0], argv);
        fprintf(stderr, "ERROR: %s", strerror(errno));
        return 1;
}

# gcc -Wall -Wextra main.c && ./a.out 
+ echo foo bar
foo bar
```
