### ISSUE TITLE
Nuspell now included as "app-text/nuspell" in Gentoo

### ISSUE THREAD

**Issue by hartwork** [nuspell/nuspell#53]
Hi!

I ran into [Sander's Nuspell talk at FOSDEM 2020](https://ftp.fau.de/fosdem/2020/AW1.120/clc_nuspell_version_3_of_the_new_spell_checker.webm) and its explicit `Help wanted` slide around 18m21s with a list that included Gentoo.  So I felt like giving packaging Nuspell for Gentoo a shot. I think it's fair to say that it was [a painless experience](https://github.com/gentoo/gentoo/commit/c2ca110efb08e18b4bd275b818ceca387c2a36f1) so far — thanks to you for that!

I would make [wiki page "Nuspell packaged binaries"](https://github.com/nuspell/nuspell/wiki/Nuspell-packaged-binaries#27-gentoo) point to the upcoming package page https://packages.gentoo.org/packages/app-text/nuspell —might take a few minutes to go out of 404— for Gentoo but it seems I lack write permissions in the Nuspell wiki.  Can you do that update for me?

Thanks and best, Sebastian

**Comment by hartwork** [comment]
PS: https://packages.gentoo.org/packages/app-text/nuspell is live by now

**Comment by PanderMusubi** [comment]
Thanks, I wiil update the wiki soon.

**Comment by dimztimz** [comment]
Thank you very much for this!

**Comment by PanderMusubi** [comment]
Dear @hartwork, we have updated the license info, it be found in https://github.com/nuspell/nuspell/blob/debian/debian/copyright

Also, we have a new version of the description which can be found at https://github.com/nuspell/nuspell/blob/debian/debian/control#L25

Please, update both for Gentoo. We try to avoid promoting we are a re-implementation, so if you could omit that part from your desciption, please. Again, thank you for including Nuspell in Gentoo.

I have also updated our wiki with your direct link. The next months we will see more packaging and that page will get more improvements.

**Comment by hartwork** [comment]
> Please, update both for Gentoo. We try to avoid promoting we are a re-implementation, so if you could omit that part from your desciption, please. Again, thank you for including Nuspell in Gentoo.

In Gentoo, allowing users to execute upstream's test suite out of the box is a feature of the package manager that packages are expected to support if possible. License…
```
test? ( || ( MPL-1.1 GPL-2+ LGPL-2.1+ ) ) LGPL-3+
```
…enforce that
- users who do not compile or run Nuspell tests need to accept license LGPL-3+ and that only
- users that do compile and run the tests also need to accept at least one of three licenses — `|| ( one two three)` is an "or" while `test? ( one )` is a conditional

That matches reality to my current best understanding. What do you want me to do?

> I have also updated our wiki with your direct link. The next months we will see more packaging and that page will get more improvements.

Just so you know: Unlike with Debian, there is only one single nuspell package in Gentoo. So if you like you can remove `Search Portage packages via https://packages.gentoo.org/packages/search?q=nuspell` as https://packages.gentoo.org/packages/app-text/nuspell should be all that gentoo users need.

**Comment by PanderMusubi** [comment]
Fixed our wiki.

Regarding the licenses, in a next release, the old source files will all be removed. The Debian packages simply don't include those files, but I see that for Gentoo that works differently. So list the licenses which you see need to be there, as you already did.

Initial reason to place my comment was to request an update of the "Full description". So that is all that remains.

**Comment by dimztimz** [comment]
Hello @hartwork . I'd like to avoid users seeing complicated licensing notes which are confusing. Let me explain,

1. Hunspell is part of the source tree,
2. but it is a third-party dependency (by source). For example, Firefox and Chromium have hundreds of third-party dependencies by source with various licenses, but one does not point the licenses of all of them.
3. The Hunspell dependency is used only in testing,
4. but it is not uses in unit testing and is not part of `ctest`/`make test`. The program `tests/verify` uses Hunspell, but that program is used only manually by us, it is not part of the default test-suite. That program is LGPL v3 or later.
5. Of the three licenses of Hunspell, the tool `tests/verify` picks "LGPL v2.1 or later", and turns that into "LGPL v3 or later". All of our test programs are "LGPL v3 or later". Thus, a user running any of the tests, including the tool `tests/verify`, complies only with that.

What I'd like you to do in the Gentoo package is either:

1. Accept that the files under `src/hunspell, src/parsers, src/tools` are just third-party dependency and follow point 2 from above. Maybe the confusing part for you was that those files are not under the directory `third-party` (in our case directory `external`). The reason for that is, well, historical. Please tell me if this was the case.
2. OR, just remove those files with a patch file and drop two lines from the `CMakeLists.txt` to disable building `tests/verify`.

Sorry for the confusing I had and you had in the past few days.

**Comment by hartwork** [comment]
> Fixed our wiki.

Looks perfect now, thank you! :+1: 

> Initial reason to place my comment was to request an update of the "Full description". So that is all that remains.

I see! I was about to copy your text in there but I now have doubts that's a good idea:
- As seen on https://packages.gentoo.org/packages/app-text/nuspell whitespace is not preserved and it's not XHTML so there is no `<ul>` and `<li>` that I would be aware of or that [would be documented](https://devmanual.gentoo.org/ebuild-writing/misc-files/metadata/index.html)
- The current `<longdescription>` provides information specific to users of Gentoo and tries to be neutral; for feature lists the Nuspell website does a good job and seems like a better place to me.

The only reason I put `<longdescription>` in there in the first place is because the `DESCRIPTION=` line has a lower limit and did not allow mentioning Hunspell.

>     2. but it is a third-party dependency (by source). For example, Firefox and Chromium have hundreds of third-party dependencies by source with various licenses, but one does not point the licenses of all of them.

In the context of a distribution they are not mentioned because they [get unbundled](https://wiki.gentoo.org/wiki/Why_not_bundle_dependencies), i.e. ripped out and replaced by a dependency on an existing package. Both Debian and Gentoo are fairly strict in that aspect. If something cannot be unbundled, I would expect that package licensing metadata reflects that nature.

>     3. The Hunspell dependency is used only in testing,

Understood.

>     4. but it is not uses in unit testing and is not part of `ctest`/`make test`. The program `tests/verify` uses Hunspell, but that program is used only manually by us, it is not part of the default test-suite. That program is LGPL v3 or later.

I am happy to add `rm -R src/{hunspell,parsers,tools} || die` into the package for the next release provided
- (that the files still exist,)
- that I can still run `make test` with the actual tests
- that I do not need to patch the build system (because the ideal downstream patch count is 0 for any distribution)

What do you think?

>     5. Of the three licenses of Hunspell, the tool `tests/verify` picks "LGPL v2.1 or later", and turns that into "LGPL v3 or later". All of our test programs are "LGPL v3 or later". Thus, a user running any of the tests, including the tool `tests/verify`, complies only with that.

I get the idea. You're arguing that if `1 + 1 + 1 = 3` we don't need to communicate the term `1 + 1 + 1`, we can just communicate the result `3`. I'm up for that once the packaging can safely delete all those files.

**Comment by PanderMusubi** [comment]
Would this work for the full description?:

`Nuspell is a free and open source spell checker that is written in modern C++. It is designed for languages with rich morphology and complex word compounding. Main features are: Full unicode support backed by ICU. Backward compatibility with Hunspell dictionary file format. Twofold affix stripping (for agglutinative languages, like Azeri, Basque, Estonian, Finnish, Hungarian, Turkish, etc.). Support complex compounds (for example, Hungarian, Germand and Dutch). Support language specific features (for example, special casing of Azeri and Turkish dotted i, or German sharp s). Handle conditional affixes, circumfixes, fogemorphemes, forbidden words, pseudoroots and homonyms.`

**Comment by hartwork** [comment]
If it matters to you, I can put something like that in there. It's not ideal though that the text is now separating things with full stops (dots) that are not actual full sentences, e.g.: `Support complex compounds (for example, Hungarian, Germand and Dutch).` Maybe semicolons or commas would work?

**Comment by hartwork** [comment]
PS: Two supposed typos:
- unicode -> Unicode
- Germand -> German

**Comment by PanderMusubi** [comment]
Thanks for your feedback. One of those typos is fixed in a branch. Let me get back to you on this in a few days and also process the rest of your feedback.

**Comment by PanderMusubi** [comment]
We will probably offer more custom documentation for packagers in our wiki soon.
