### ISSUE TITLE
Consider moving hunspell files to the directory external

### ISSUE THREAD

**Issue by dimztimz** [nuspell/nuspell#54]
Do this to avoid confusion for downstream users like the one discussed in #51. This is low-priority right now and it may be done somewhere for version 4.x. For 3.x the current directory structure suits me better.

**Comment by PanderMusubi** [comment]
When these fiels are moved out, we can also move the verification application of here. Perhaps move the verification application to misc-nuspell and only when building let it pull in hunspell files locally.

**Comment by dimztimz** [comment]
That one is good as it is.
