### ISSUE TITLE
OpenMandriva support nuspell

### ISSUE THREAD

**Issue by tpgxyz** [nuspell/nuspell#55]
Hi,
i'd like to announce that OpenMandriva Linux distribution has packaged nuspell, like i've promised to do that to you on FOSDEM2020 :)

How to install it ?
`dnf install nuspell`

Sources:
https://github.com/OpenMandrivaAssociation/nuspell

**Comment by PanderMusubi** [comment]
Thank you very much! I have added it to our [wiki](https://github.com/nuspell/nuspell/wiki/Nuspell-packaged-binaries#29-openmandriva).

One change is needed however, the license is `LGPL-3+`

Do you also know of an online package search for OpenMandriva?

**Comment by tpgxyz** [comment]
@PanderMusubi  Hi, ive updated licese, and you can check https://pkgs.org/download/nuspell

**Comment by tpgxyz** [comment]
BTW any plans to integrate nuspell with KDE ?

**Comment by PanderMusubi** [comment]
Thanks.

Which part of KDE do you mean? At the moment we are integrating via Enchat and Firefox and after that LibreOffice. Meanwhile, Nuspell is being packaged for many distributions. When those packages are available, it is easy for maintainers of applications to make their own integration, which is only a minor change compared to existing spell checking integrations and we will have plenty of examples on how to do that.

**Comment by tpgxyz** [comment]
@PanderMusubi I mean https://github.com/KDE/sonnet

Anyways if nuspell is about to replace hunsplell, would be nice to provide by nuspell a drop-in replacement in .h and .pc files

**Comment by PanderMusubi** [comment]
Thanks for the link. I have put it on the list of integrations for after we have completed full support for personal dictionaries and sessions.
