### ISSUE TITLE
Base usage of library

### ISSUE THREAD

**Issue by Tectu** [nuspell/nuspell#56]
I'm considering integrating nuspell into a Qt based text editor component. Unfortunately, I couldn't find a lot of documentation on how to use the nuspell library in a consuming application.

I have no problems building & integrating nuspell in the existing application. My question is: Where to go from here? What is the intended way of using nuspell to check a given text (not just single word) against the dictionary and then retrieving back the information such as the position (?) of words that are misspelled and the corresponding suggestions?

From quickly browsing through the source code I guess that `Dictionary::spell()` is the way to go here. However, I am not sure where to find the information regarding the parameter: Can this be an entire text block or am I supposed to manually iterate over all the words in my text and call `Dictionary::spell()` on each word?

I'd be thankful for any kind of information that would point me towards using nuspell the intended way.

**Comment by PanderMusubi** [comment]
Thanks for your question. I was planning to write a about this in the wiki with some more examples. The best is you can break the text up into separate words yourself and call the methods to check the spelling and get suggestion per word.

We have some example code to tokenize plain text, if that is what you have. But it depends greatly on the format of your text. Could you send me a link to the repository you are working in?

**Comment by dimztimz** [comment]
There is a short example in the README, please give it a look.

> However, I am not sure where to find the information regarding the parameter: Can this be an entire text block or am I supposed to manually iterate over all the words in my text and call Dictionary::spell() on each word?

You need to tokenize the text to words and call Nuspell functions word by word. The recommended way to get the words of a text is [Unicode text segmentation](https://www.unicode.org/reports/tr29/) which is already implemented in ICU and [QT](https://doc.qt.io/qt-5//qtextboundaryfinder.html).

**Comment by PanderMusubi** [comment]
@Tectu see also https://github.com/nuspell/nuspell/wiki/Using-the-software-library

**Comment by dimztimz** [comment]
The linked wiki page is good enough now, I'm closing this.
