### ISSUE TITLE
Universal Linux packages

### ISSUE THREAD

**Issue by dimztimz** [nuspell/nuspell#57]
Universal Linux packages are independent of the distribution. There are 3 popular solutions for making universal packages for Linux. Those are:

- [x] [AppImage](https://appimage.org/)
- [x] Snappy
- [x] [Flatpak](https://flatpak.org/)

At least one should be made and my vote is to make package with AppImage as it is the most universal, it comes preinstalled on all major Linux distros.

**Comment by PanderMusubi** [comment]
For AppImage, see https://github.com/nuspell/misc-nuspell/tree/master/packaging/appimage

**Comment by PanderMusubi** [comment]
For Flatpak, see https://github.com/nuspell/misc-nuspell/tree/master/packaging/flatpak

**Comment by PanderMusubi** [comment]
For Snap, see https://github.com/nuspell/misc-nuspell/tree/master/packaging/snap

**Comment by dimztimz** [comment]
Reopening this because the AppImage and Flatpak are incomplete.

We had 2 attempts for AppImage but to create truly portable ones, it should be done with the tool [AppImage Builder](AppImageCrafters/appimage-builder).

The Flatpak has some bugs which are tracked here https://github.com/flathub/flathub/pull/1502

**Comment by PanderMusubi** [comment]
https://github.com/nuspell/nuspell/releases/download/v3.1.1/Nuspell-3.1.1-x86_64.AppImage

**Comment by PanderMusubi** [comment]
See https://github.com/nuspell/misc-nuspell/tree/master/packaging/flatpak
