### ISSUE TITLE
Dealing with words with more than two prefixes

### ISSUE THREAD

**Issue by sinaahmadi** [nuspell/nuspell#58]
Hi,

I am working on a morphologically-rich language where a lemma can have many prefixes and suffixes.

Let's suppose my `.aff` file contains the following:

```
SET UTF-8
COMPLEXPREFIXES

PFX A Y 1
PFX A 0 e

PFX B Y 1
PFX B 0 d/A

PFX C Y 1
PFX C 0 f/B

SFX V Y 1
SFX V 0 x/C .
```
and my `.dic` file contains the following:

```
1
H/V
```

Although I am able to analyze words with two or less than two prefixes, like `dfHx`, I cannot analyze strings with more than two prefixes, e.g. `edfHx`. Is there any solution to this? 

In the [Hunspell's documentation](http://manpages.ubuntu.com/manpages/trusty/en/man4/hunspell.4.html) and [that of Nuspell](https://github.com/nuspell/nuspell/wiki/Affix-File-Format), we read that:

>  Ispell's original algorithm strips only one suffix. Hunspell can strip another one yet (or
       a plus prefix in COMPLEXPREFIXES mode).

and also,

> COMPLEXPREFIXES
              Set  twofold prefix stripping (but single suffix stripping) eg. for morphologically
              complex languages with right-to-left writing system.

Do these mean that Nuspell and Hunspell cannot handle words with more than two prefixes? 

I have looked into the implementation of similar languages, like [Hungarian](https://github.com/elastic/hunspell/blob/master/dicts/hu/hu.aff), but could not find any solution.

Thanks for your help.

**Comment by shaflan** [comment]
Dear @sinaahmadi, may I ask how you did manage it to work? I assume you closed it because there was a solution. Thank you. 
- Shaflan

**Comment by sinaahmadi** [comment]
Hi Shaflan,
I asked this question when I was learning about Hunspell. I later designed my project in my way. Here is the .aff file: https://github.com/sinaahmadi/KurdishHunspell/blob/main/ckb/ckb-Arab.aff 
I hope this help.

**Comment by shaflan** [comment]
Thank you very much. 
- Shaflan
