### ISSUE TITLE
Logo proposal for NUSPELL

### ISSUE THREAD

**Issue by ggabogarcia** [nuspell/nuspell#6]
Hello, I'm a graphic designer and I like to collaborate with open source projects. I would like to design a logo for your [Project](https://opensourcedesign.net/jobs/jobs/2017-11-30-logo-for-spelling-checker-nuspell) I will be happy to collaborate with you :)

**Comment by PanderMusubi** [comment]
Sorry for the late reply, I though I had posted a reply here. We have two submissions up to now. If you want, you send your idea or concept to us via https://opensourcedesign.net/jobs/jobs/2017-11-30-logo-for-spelling-checker-nuspell and we will take it into consideration too. We also have to look at the other submissions.

**Comment by ggabogarcia** [comment]
@PanderMusubi  Hello, thank you very much for your reply :), it's fine, I'll do the design and send it to the email they provide. Thanks again :)

**Comment by PanderMusubi** [comment]
Meanwhile, we have a logo and several formats can be found in https://github.com/nuspell/nuspell.github.io/tree/master/assets/images
