### ISSUE TITLE
openSUSE build of nuspell

### ISSUE THREAD

**Issue by kevinsmia1939** [nuspell/nuspell#67]
I create package for nuspell in openSUSE, currently waiting to be accept into M17N.

https://build.opensuse.org/package/show/home:andythe_great/nuspell
https://build.opensuse.org/request/show/793270

**Comment by PanderMusubi** [comment]
@kevinsmia1939 Thanks for packaging! We refer to it from here now: https://github.com/nuspell/nuspell/wiki/Nuspell-packaged-binaries#opensuse
