### ISSUE TITLE
Is it LGPL or GPL?

### ISSUE THREAD

**Issue by kevinsmia1939** [nuspell/nuspell#68]
There are 2 license included.

COPYING.LESSER and COPYING which contain LGPL v3 or later and GPL v3, which one is it? 
The documentation say that it is LGPL v3 or later, so could you consider removing the GPL v3?
Thanks.

**Comment by dimztimz** [comment]
It is LGPL.

https://www.gnu.org/licenses/gpl-howto.html

> - Add a COPYING file with a copy of the GNU GPL or GNU AGPL.
> - Also add a COPYING.LESSER file with a copy of the GNU LGPL, if you use that.

**Comment by kevinsmia1939** [comment]
Not sure if I read it correctly, but do you have to include GPL even if it only license under LGPL?

**Comment by dimztimz** [comment]
That is correct.
