### ISSUE TITLE
Could not build on openSUSE Tumbleweed: E: lto-no-text-in-archive 

### ISSUE THREAD

**Issue by kevinsmia1939** [nuspell/nuspell#73]
Hello,
I try to update Nuspell package to 3.1.1 on openSUSE Tumbleweed.

I encounter an error which prevent it from building.
```
[  265s] nuspell-devel.x86_64: E: lto-no-text-in-archive (Badness: 10000) /usr/lib64/libnuspell.a
[  265s] This archive does not contain a non-empty .text section.  The archive was not
[  265s] created with -ffat-lto-objects option.
```
The error suggest adding  -ffat-lto-objects but this is seen as a work around and must be fix.

openSUSE Wiki suggest adding the flag as well, but it is consider outdate and workaround is bad.
https://en.opensuse.org/openSUSE:LTO
I do not have much knowledge on this error, I will ask other packager if you need some help. 

Full build log: https://build.opensuse.org/package/live_build_log/home:andythe_great/nuspell/openSUSE_Tumbleweed/x86_64

**Comment by dimztimz** [comment]
You are not building a shared library. https://cmake.org/cmake/help/latest/variable/BUILD_SHARED_LIBS.html

Please see the readme https://github.com/nuspell/nuspell/blob/master/README.md#building-on-gnulinux-and-unixes

**Comment by kevinsmia1939** [comment]
> You are not building a shared library. https://cmake.org/cmake/help/latest/variable/BUILD_SHARED_LIBS.html
> 
> Please see the readme https://github.com/nuspell/nuspell/blob/master/README.md#building-on-gnulinux-and-unixes

You are right, got it now.
