### ISSUE TITLE
Consider replacing wchar_t with char32_t

### ISSUE THREAD

**Issue by dimztimz** [nuspell/nuspell#76]
This might be needed to avoid the quirks that `wchar_t` has, i.e. having different size on different platforms, thus storing UTF-16 or UTF-32. Our code handles this difference by having different code paths for the one and the another case, but this is not elegant solution.

The change is mostly find and replace. It should be done as follows:

1. Replace `wchar_t` with `char32_t`.
2. Replace `wstring` with `u32string`.
3. Replace wide string literals to UTF-32 string literals, e.g. `L"abc"` to `U"abc"`.
4. Remove  UTF-16 codepaths, e.g. search for `U_SIZEOF_WCHAR_T`.
5. Optionally rename some functions and classes to not use the word `wide`, but use `u32`.

Contributors are welcomed to do a PR up to this point. We will do the performance testing to see if this change is acceptable.

Change like this is ABI breaking because it changes the type of data members of class Dictionary. If done, major version should be bumped. Public API will stay unmodified.

**Comment by hsivonen** [comment]
How long-lived are these strings? Is there a good reason not to use UTF-8 strings in the interest of lesser memory usage and cache pressure?

**Comment by dimztimz** [comment]
Hello Henri.

Nuspell does a lot of string manipulation at the level of code points, therefore things are like this. I suspect UTF-8 might slow things too much. In the future, I'm considering to implement abstraction layer for easy code point manipulation. With such layer I would be able to relatively easily switch the character type (char, char32_t, char16_t) and the Unicode transformation formats, and I would be able to do measurements which one is the fastest.

**Comment by hsivonen** [comment]
I think "fastest" isn't the only relevant metric if these strings are kept in memory so that they contribute to the RAM footprint of the application on an ongoing basis.

Iterating over UTF-8 by scalar value is pretty fast. Storing Unicode as UTF-8 in RAM but iterating over it by Unicode scalar value is idiomatic e.g. in Rust, and works well. UTF-8 storage puts less pressure on CPU caches and, therefore, can have a good effect on overall application speed in a way that does not show up on microbenchmarks.

**Comment by dimztimz** [comment]
Conversion to UTF-8 for internal strings has been finished see https://github.com/nuspell/nuspell/issues/80#issuecomment-802018424 .

Only at few places UTF-32 is used via the type `char32_t` now. See 843bdad8563db2f0bf7a69b2a404443efb2b47f2.
