### ISSUE TITLE
Nuspell now officially in openSUSE Tumbleweed, but there are issue with Leap.

### ISSUE THREAD

**Issue by kevinsmia1939** [nuspell/nuspell#77]
Hi,

Nuspell have been officially accept to openSUSE Tumbleweed. 
https://software.opensuse.org/package/nuspell

openSUSE Tumbleweed can install it with
 sudo zypper in nuspell

However, there are issue about builing nuspell on leap.
The test failed when  testing legacy_test, not sure what happen.

https://build.opensuse.org/package/live_build_log/M17N/nuspell/openSUSE_Leap_15.2/x86_64

**Comment by dimztimz** [comment]
This is a bug on the side of openSUSE in the invocation of Cmake. It disables rpath by giving DCMAKE_SKIP_RPATH:BOOL=ON to cmake.

Closing here.

**Comment by kevinsmia1939** [comment]
Thanks, turn off the flag and it build on leap now.
