### ISSUE TITLE
Plans for Binary Release

### ISSUE THREAD

**Issue by mbarkhau** [nuspell/nuspell#78]
Are there plans for binary releases, (preferably statically linked) for various platforms?

I just had a look at creating binaries for hunspell using GitHub Actions, perhaps that would be an option to make this automated?

https://github.com/mbarkhau/hunspell/runs/936292735?check_suite_focus=true

**Comment by sjrmanning** [comment]
+1 — it'd be great to be able to `brew install` on macOS too, which this could facilitate.

**Comment by PanderMusubi** [comment]
Regarding brew, we already have a Formula for Nuspell. To get included into the main brew repo, we need 30+ forks, 30+ watchers and 75+ stars for the Nuspell repository here at GitHub.

**Comment by sjrmanning** [comment]
I see! I'll use the nuspell tap for now, and do what I can to help hit that milestone. Thanks!

**Comment by dimztimz** [comment]
@mbarkhau Please see this https://github.com/nuspell/nuspell/wiki/Nuspell-packaged-binaries

**Comment by mbarkhau** [comment]
Ok then, I guess this is out of scope.
