### ISSUE TITLE
Simplest script that installs all of the dictionaries and wordlists on Debian

### ISSUE THREAD

**Issue by dimztimz** [nuspell/nuspell#88]
# Feature request

If we run the following on Debian or Ubuntu:

```sh
$ apt show wdutch
Package: wdutch
...
Installed-Size: 4 266 kB
Provides: wordlist
Depends: dictionaries-common, debconf (>= 0.5) | debconf-2.0
...
```

We can notice that all wordlists are marked with `Provides: wordlist`.

Same goes for dictionaries:

```sh
$ apt show hunspell-nl
Package: hunspell-nl
...
Installed-Size: 2 497 kB
Provides: hunspell-dictionary, hunspell-dictionary-nl, myspell-nl
Depends: dictionaries-common | openoffice.org-updatedicts
Conflicts: myspell-nl
Replaces: myspell-nl
...
```

Find out the simplest script that:

- will use those fields,
- has no hardcoded values, or the least possible,
- is future proof, i.e. if a new dictionary is added in a new Debian version, the script should detect it,
- is in one line and at most 50 chars, so it is easily copied and pasted. If this limit can not be satisfied in any way, it should be broken into multiple lines.

What have I tried so far is bellow.

```sh
sudo apt install wordlists
sudo apt install hunspell-dictionary
```

That does not work.

**Comment by PanderMusubi** [comment]
Does this suffice?

Dictionaries:

    for i in $(apt-cache search ^hunspell-|awk '{print $1}'); do if [ $(apt-cache show $i|grep ^Provides|grep -c hunspell-dictionary) -ne 0 ]; then echo $i; fi; done

Wordlists:

    for i in $(apt-cache search ^w..*|awk '{print $1}'); do if [ $(apt-cache show $i|grep ^Provides|grep -c wordlist) -ne 0 ]; then echo $i; fi; done

**Comment by dimztimz** [comment]
See this https://serverfault.com/questions/364608/how-do-i-get-a-list-of-packages-that-provides-something-using-dpkg

**Comment by PanderMusubi** [comment]
Shorter is

    aptitude search '~Phunspell-dictionary'|awk '{print $2}'

Note that there are also dummy and transitional packages.

    aptitude search '~Pwordlist'|awk '{print $2}'

Note that there are many sizes of American, British and Canadian word lists.

**Comment by dimztimz** [comment]
That doesn't install anything, only prints the names.

**Comment by PanderMusubi** [comment]
sudo apt-get -y install $(aptitude search '~Pwordlist'|awk '{print $2}'|sed -e 's/\n/ /g')

**Comment by dimztimz** [comment]
```
E: Unable to locate package A
E: Unable to locate package A
```

**Comment by PanderMusubi** [comment]
Works fine for me one multiple Ubuntu versions, https://pastebin.com/YtZbgULB Do you have more info how you got that error?

**Comment by dimztimz** [comment]
Tried again on Ubuntu 20.04 and the same error remains. However, I just updated the constrains in the first post.

> - is in one line and at most 50 chars, so it is easily copied and pasted. If this limit can not be satisfied in any way, it should be broken into multiple lines.

You can use aptitute in a much better way that you are using now.

**Comment by PanderMusubi** [comment]
Does this solve it?

    sudo apt-get -y install \
    $(aptitude search -F '%p' ~Pwordlist|tr '\n' ' ')

**Comment by dimztimz** [comment]
Have you considered using `aptitude install`?

**Comment by PanderMusubi** [comment]
Not yet, but when using it, we get

    sudo aptitude install ~Pwordlist

**Comment by dimztimz** [comment]
Ok, that one works. What about dictionaries, find an easy command for dictionaries that meets the criteria in the first post. It MUST install them, not list them.

**Comment by PanderMusubi** [comment]
With

    sudo aptitude install ~Phunspell-dictionary

you can see the before mentioned issues with the dictionaries come forward. It will prompt the conflicts and offer solutions. However the suggested solutions are not optimal. Either an older Myspell dictionary is preferred over a Hunspell dictionay, e.g.:

     hunspell-es : Conflicts: myspell-es but 1.11-15 is to be installed

or only one of a multiple current (valuable) dictionaries is suggested, e.g.:

     hunspell-fr-revised : Conflicts: hunspell-fr-classical but 1:6.4.1-1 is to be installed
                           Conflicts: hunspell-fr-comprehensive but 1:6.4.1-1 is to be installed
                           Conflicts: hunspell-fr-modern but 1:6.4.1-1 is to be installed
                           Conflicts: myspell-fr but 1.4-27 is to be installed

The package restrictions are there because the packages want to install dictionaries with identical file paths, e.g. /usr/share/hunspell/fr.dic etc. Aptitude probably makes suggestions based on the version number, which is not installing the most used/relevant dictionary.

My approach was not to install them on the system, but download the packages in a directory and extract them in subdirectories named after their package. In that way, all dictionaries can be used for testing. However, such command(s) would not meet the criteria in the first post. What are your thoughts on this?

**Comment by dimztimz** [comment]
Ok, make a command that will exclude the conflicting dictionaries, having few hard-coded values is OK. Leave the best, or, leave the one that is considered the default. Aptitude has some powerful mechanism for [searching packages](https://www.debian.org/doc/manuals/aptitude/ch02s04.en.html) (look mostly in the section Search term reference). For example:

    sudo aptitude install ~Phunspell-dictionary !myspell-fr

**Comment by PanderMusubi** [comment]
Try this:

    sudo aptitude install "~P"hunspell-dictionary" ~n!"myspell-es" ~n!"myspell-fr" ~n!"hunspell-fr-classical" ~n!"hunspell-fr-revised" ~n!"hunsepll-fr-modern" ~n!"hunspell-de-de" ~n!"hunspell-de-at" ~n!"hunspell-de-ch""

Tested on Ubuntu 20.04 and 20.10.

**Comment by dimztimz** [comment]
Simpler, with less quotes:

```
sudo aptitude install '~Phunspell-dictionary !myspell-es !myspell-fr !hunspell-fr-classical !hunspell-fr-revised !hunsepll-fr-modern !hunspell-de-de !hunspell-de-at !hunspell-de-ch'
```

Snooping around I found another command to list packages that provide a virtual package, better than the one on the serverfault above.

```
apt-cache search --names-only hunspell-dictionary
apt-cache search --names-only wordlist
```

With some awk to select the first column and grep to exclude lines we can achieve the same without aptitude, but its more complicated.

**Comment by PanderMusubi** [comment]
Shall I upgrade https://github.com/nuspell/nuspell.verification with the above commands?

**Comment by dimztimz** [comment]
The last task is to create set of command that will do the following:

1. list all word-lists;
2. install all word-lists;
3. list all dictionaries;
4. install all dictionaries.

All of this should be done without aptitude, and with the the default installed tools like `apt-get, apt-cache, grep`. See https://github.com/nuspell/nuspell/issues/88#issuecomment-716206677

**Comment by PanderMusubi** [comment]
apt-cache search -n wordlist|awk '{print $1}'
    sudo apt-get install $(apt-cache search -n wordlist|awk '{print $1}'|tr '\n' ' ')
    apt-cache search -n hunspell-dictionary|awk '{print $1}'
    sudo apt-get install $(apt-cache search --names-only hunspell-dictionary|awk '{print $1}'|grep -v myspell-es|grep -v myspell-fr|grep -v hunspell-fr-classical|grep -v hunspell-fr-revised|grep -v hunspell-fr-modern|grep -v hunspell-de-de|grep -v hunspell-de-at|grep -v hunspell-de-ch|tr '\n' ' ')

**Comment by dimztimz** [comment]
`tr` is not needed. Only one invocation of grep is needed.

**Comment by PanderMusubi** [comment]
apt-cache search -n wordlist|awk '{print $1}'
    sudo apt-get install $(apt-cache search -n wordlist|awk '{print $1}')
    apt-cache search -n hunspell-dictionary|awk '{print $1}'
    sudo apt-get install $(apt-cache search --names-only hunspell-dictionary|awk '{print $1}'|grep -v myspell-es|grep -v myspell-fr|grep -v hunspell-fr-classical|grep -v hunspell-fr-revised|grep -v hunspell-fr-modern|grep -v hunspell-de-de|grep -v hunspell-de-at|grep -v hunspell-de-ch)

**Comment by dimztimz** [comment]
Only one call to grep can do the same job.
