### ISSUE TITLE
Byte-offsets option for nuspell command

### ISSUE THREAD

**Issue by voroskoi** [nuspell/nuspell#92]
Hi,

I would like to use a `--byte-offsets` option in nuspell cli application similar to the one in aspell. This would output the misspelled word offset from line start in bytes, not chars.

Please let me know if You are open for such a PR or not.

Thanks,

**Comment by dimztimz** [comment]
This is already the case in the latest version.

**Comment by voroskoi** [comment]
Sorry, I was looking for the option, I did not know it is the default behavior.

**Comment by voroskoi** [comment]
I just wanted to report back that is works perfectly for me with English and Hungarian as well. Thank you!
