### ISSUE TITLE
nuspell: please remove haskell dependency

### ISSUE THREAD

**Issue by 0-wiz-0** [nuspell/nuspell#93]
In 4.0.1 the man page is generated with pandoc, which is written in Haskell. ghc (the main Haskell compiler) is not the most portable software and quite large to boot.
Can you please include the generated man page inside the distribution tarball?

**Comment by dimztimz** [comment]
I don't see how this is a problem. We depend on pandoc which is already offered as **pre-compiled** package on many many operating systems. There is no dependency on GHC.

**Comment by 0-wiz-0** [comment]
I'm packaging for pkgsrc which is the default package system for NetBSD (but available on lots of other platforms).
ghc is not available on all of these, so neither is pandoc.

**Comment by 0-wiz-0** [comment]
Also since you have pandoc, it should be easy for you to generate the man page and include it in the tarball.
