### ISSUE TITLE
Dictionary not found in fedora

### ISSUE THREAD

**Issue by vishalvvr** [nuspell/nuspell#94]
# Change/feature request
Nuspell looks for dictionaries in /usr/share/hunspell/, but they're actually in /usr/share/myspell/.

Is it possible to add another path for dictionary searching? or a config file to override the default behaviour? 

Note:
This bug was reported against [fedora 33](https://bugzilla.redhat.com/show_bug.cgi?id=1892402)

**Comment by PanderMusubi** [comment]
You can use the environment variable `DICPATH` to add (colon separated) paths to search for. Does that help?

**Comment by PanderMusubi** [comment]
See also https://bugzilla.redhat.com/show_bug.cgi?id=1807365

**Comment by dimztimz** [comment]
Some investigation shows that:

1. Most distributions use `/usr/share/hunspell`
2. Fedora uses `/usr/share/myspell`
3. Debian (Ubuntu) and Arch fill `/usr/share/myspell/dicts` with symbolic links to files into `/usr/share/hunspell`.
4. FreeBSD uses `/usr/local/share/hunspell`.

To even further generalize the variance with `/usr` and `/usr/local`, this specification should be used https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html .

The conclusion is `$XDG_DATA_DIRS/hunspell` and `$XDG_DATA_DIRS/myspell` should be searched, and `$XDG_DATA_DIRS/myspell/dicts` should not be searched.
